import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/contexts/AuthContext";
import { HospitalInfoProvider } from "@/contexts/HospitalInfoContext";
import { AppointmentProvider } from "@/contexts/AppointmentContext";
import { DoctorProvider } from "@/contexts/DoctorContext";
import { StaffProvider } from "@/contexts/StaffContext";
import { SurgeryProvider } from "@/contexts/SurgeryContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HospitalInfoProvider>
          <SurgeryProvider>
            <StaffProvider>
              <DoctorProvider>
                <AppointmentProvider>
                    <AuthProvider>
                      {children}
                    </AuthProvider>
                </AppointmentProvider>
              </DoctorProvider>
            </StaffProvider>
          </SurgeryProvider>
        </HospitalInfoProvider>
      </body>
    </html>
  );
}
